import { Injectable } from '@angular/core';
import { Countrydata } from './interface';
@Injectable({
  providedIn: 'root',
})
export class CountryList {
  countryList: Countrydata[] = [
    { country: 'Alaska', code: 'AK', isSelected: false },
    { country: 'Alabama', code: 'AL', isSelected: false },
    { country: 'Arkansas', code: 'AR', isSelected: false },
    { country: 'Arizona', code: 'AZ', isSelected: false },
    { country: 'California', code: 'CA', isSelected: false },
    { country: 'Colorado', code: 'CO', isSelected: false },
    { country: 'Connecticut', code: 'CT', isSelected: false },
    { country: 'Delaware', code: 'DE', isSelected: false },
    { country: 'Florida', code: 'FL', isSelected: false },
    { country: 'Georgia', code: 'GA', isSelected: false },
    { country: 'Hawaii', code: 'HI', isSelected: false },
    { country: 'Lowa', code: 'IA', isSelected: false },
    { country: 'Idaho', code: 'ID', isSelected: false },
    { country: 'Illinois', code: 'IL', isSelected: false },
    { country: 'Indiana', code: 'IN', isSelected: false },
    { country: 'Kansas', code: 'KS', isSelected: false },
    { country: 'Kentucky', code: 'KY', isSelected: false },
    { country: 'Louisiana', code: 'LA', isSelected: false },
    { country: 'Massachusetts', code: 'MA', isSelected: false },
    { country: 'Maryland', code: 'MD', isSelected: false },
    { country: 'Maine', code: 'ME', isSelected: false },
    { country: 'Michigan', code: 'MI', isSelected: false },
    { country: 'Minnesota', code: 'MN', isSelected: false },
    { country: 'Missouri', code: 'MO', isSelected: false },
    { country: 'Mississippi', code: 'MS', isSelected: false },
    { country: 'Montana', code: 'MT', isSelected: false },
    { country: 'North Carolina', code: 'NC', isSelected: false },
    { country: 'North Dakota', code: 'ND', isSelected: false },
    { country: 'Nebraska', code: 'NE', isSelected: false },
    { country: 'New Hampshire', code: 'NH', isSelected: false },
    { country: 'New Jersey', code: 'NJ', isSelected: false },
    { country: 'New Mexico', code: 'NM', isSelected: false },
    { country: 'Nevada', code: 'NV', isSelected: false },
    { country: 'New York', code: 'NY', isSelected: false },
    { country: 'Ohio', code: 'OH', isSelected: false },
    { country: 'Oklahoma', code: 'OK', isSelected: false },
    { country: 'Oregon', code: 'OR', isSelected: false },
    { country: 'Pennsylvania', code: 'PA', isSelected: false },
    { country: 'Rhode Island', code: 'RI', isSelected: false },
    { country: 'South Carolina', code: 'SC', isSelected: false },
    { country: 'South Dakota', code: 'SD', isSelected: false },
    { country: 'Tennessee', code: 'TN', isSelected: false },
    { country: 'Texas', code: 'TX', isSelected: false },
    { country: 'Utah', code: 'UT', isSelected: false },
    { country: 'Virginia', code: 'VA', isSelected: false },
    { country: 'Vermont', code: 'VT', isSelected: false },
    { country: 'Washington', code: 'WA', isSelected: false },
    { country: 'Wisconsin', code: 'WI', isSelected: false },
    { country: 'West Virginia', code: 'WV', isSelected: false },
    { country: 'Wyoming', code: 'WY', isSelected: false },
    { country: 'District of Columbia', code: 'DC', isSelected: false },
    { country: 'American Samoa', code: 'AS', isSelected: false },
    { country: 'Guam', code: 'GU', isSelected: false },
    { country: 'Northern Mariana Islands', code: 'MP', isSelected: false },
    { country: 'Ouerto Rico', code: 'PR', isSelected: false },
    { country: 'U.S.Virgin Islands', code: 'VI', isSelected: false },
    { country: 'Federated Stats of Micronesia', code: 'FM', isSelected: false },
    { country: 'Marshall Islands', code: 'MH', isSelected: false },
    { country: 'Palau', code: 'PW', isSelected: false },
  ];
}
